### PR TITLE
Support Python 3.4

### PR DESCRIPTION
**Pull request by eight04**

### CODE REVIEW

**Comment by eight04** [comment]
Ref: https://github.com/google/python-subprocess32/issues/53#issuecomment-396117556

subprocess32 is not going to support Python 3.4. Let's encourage users to upgrade. It shouldn't be too hard to upgrade from 3.4 to 3.5/3.6 IMHO.

**Comment by EliMCGamerGuy** [comment]
it's at times like these i wished my windows XP machine wasn't as much of a fossil than it is.

I've been making a screensaver for it in python on my windows 10 machine, everything was going fine until i started to use subprocess everything works fine on my windows 10 machine, but clearly cannot on the XP machine, as the last version of python that supported windows XP was 3.4.

**Comment by eight04** [comment]
Are you talking about subprocess32 or pyxcute? For pyxcute, since we don't depend on subprocess32 anymore, I think it should be able to run on python 3.4.

**Comment by EliMCGamerGuy** [comment]
you know what? i'm in the wrong place.

**Pull request merged**
